name: IaCセキュリティ分析

on:
  pull_request:
    paths:
      - "**/*.tf"
      - "**/*.tfvars"
      - "**/Chart.yaml"
      - "**/*.yaml"
      - "**/*.yml"
    branches: [main, develop]

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  iac-analysis:
    runs-on: ubuntu-latest
    name: インフラストラクチャ分析

    steps:
      - name: チェックアウト
        uses: actions/checkout@v4

      - name: Node.js セットアップ
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Terraform セットアップ
        uses: hashicorp/setup-terraform@v3
        with:
          terraform-version: "1.5.0"

      - name: Helm セットアップ
        uses: azure/setup-helm@v4
        with:
          version: '3.12.0'

      - name: 依存関係インストール
        run: npm ci

      - name: iac-explain ビルド
        run: npm run build

      - name: Terraform分析実行
        id: terraform-analysis
        run: |
          # すべてのTerraformディレクトリを検索
          terraform_dirs=$(find . -name "*.tf" -type f | xargs dirname | sort -u | grep -v ".terraform")

          for dir in $terraform_dirs; do
            echo "Terraformを分析中: $dir"
            cd "$dir"

            # バックエンドなしで初期化
            terraform init -backend=false

            # プラン作成
            terraform plan -no-color -out=tfplan.bin || true

            # プランが存在する場合JSONに変換
            if [ -f tfplan.bin ]; then
              terraform show -json tfplan.bin > tfplan.json

              # iac-explain 分析実行
              node ../../dist/packages/mcp-server/cli.js analyze-plan \
                --workspace . \
                --plan-path tfplan.json \
                --output analysis-${{ github.sha }}.md
            fi

            cd - > /dev/null
          done

      - name: Kubernetes分析実行
        id: kubernetes-analysis
        run: |
          # すべてのKubernetesマニフェストファイルを検索
          k8s_files=$(find . -name "*.yaml" -o -name "*.yml" | grep -v ".github" | grep -v "node_modules")

          for file in $k8s_files; do
            echo "Kubernetesマニフェストを分析中: $file"

            node dist/packages/mcp-server/cli.js validate-k8s \
              --manifests-dir $(dirname "$file") \
              --output k8s-analysis-$(basename "$file").md || true
          done

      - name: 分析結果コメント
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        with:
          script: |
            const fs = require('fs');
            const path = require('path');

            // すべての分析ファイルを検索
            const analysisFiles = fs.readdirSync('.').filter(f =>
              f.startsWith('analysis-') || f.startsWith('k8s-analysis-')
            );

            if (analysisFiles.length === 0) {
              console.log('分析ファイルが見つかりません');
              return;
            }

            let comment = '# 🔍 インフラストラクチャセキュリティ分析\n\n';

            for (const file of analysisFiles) {
              try {
                const content = fs.readFileSync(file, 'utf8');
                comment += `## ${file}\n\n${content}\n\n`;
              } catch (error) {
                console.error(`${file}の読み込みエラー:`, error);
              }
            }

            comment += '\n---\n*分析は [iac-explain](https://github.com/ryok/iac-explain) により実行されました*';

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });

      - name: 分析結果アーティファクトアップロード
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: iac-analysis-results
          path: |
            analysis-*.md
            k8s-analysis-*.md
            **/tfplan.json
          retention-days: 30

      # オプション: 重大なセキュリティ問題が発見された場合にジョブを失敗させる
      - name: 重大な問題チェック
        run: |
          critical_count=$(grep -r "severity.*crit" analysis-*.md k8s-analysis-*.md 2>/dev/null | wc -l || echo 0)

          if [ "$critical_count" -gt 0 ]; then
            echo "❌ $critical_count 件の重大なセキュリティ問題が発見されました"
            echo "::error::重大なセキュリティ問題が検出されました。マージ前に確認・修正してください。"
            # 重大な問題でビルドを失敗させる場合は次の行のコメントを外してください
            # exit 1
          else
            echo "✅ 重大なセキュリティ問題は発見されませんでした"
          fi